[character]
success_symbol = "[â¯](bold green)"
error_symbol = "[â¯](bold red)"
vicmd_symbol = "[â®](bold yellow)"

[env_var]
format = 'with ğŸš[FOO=$env_value]($style)'
variable = 'FOO'
style = 'bright-green bold'

[status]
disabled = false
